spring:
  application:
    name: user-management-service
  flyway:
    enabled: true
    schemas: ${spring.application.name}
  datasource:
    url: ${DB_HOST}/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${spring.application.name}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ${spring.application.name}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

auth:
  secret-key: ${SECRET_KEY}

server:
  port: 8082

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_HOST}/eureka


